name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every 24h
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fork Sync
        # You may pin to the exact commit or the version.
        # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
        uses: tgymnich/fork-sync@v1.2.1
        with:
          # Token for the github API
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Branch to track
          head: main
          # Branch to keep updated
          base: main
          
