# Tên của workflow, sẽ hiển thị trong tab "Actions" của GitHub
name: syns fork

# Cấu hình khi nào workflow sẽ chạy
on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  # Tên của job, bạn có thể đặt tùy ý
  sync:
    # Sử dụng máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest

    # === BẮT ĐẦU PHẦN SỬA LỖI ===
    # Cấp quyền cho GITHUB_TOKEN để có thể push code và cập nhật workflows
    permissions:
      contents: write
    # === KẾT THÚC PHẦN SỬA LỖI ===

    steps:
      # Bước 1: Checkout code từ repository của bạn (bản fork)
      - name: 1. Checkout repository của bạn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Bước 2: Thêm remote trỏ đến repository gốc (upstream)
      - name: 2. Thêm remote upstream
        run: |
          # THAY THẾ URL BÊN DƯỚI bằng URL của repository gốc mà bạn đã fork
          git remote add upstream https://github.com/danny-avila/LibreChat.git

      # Bước 3: Lấy (fetch) các thay đổi từ repository gốc
      - name: 3. Lấy các thay đổi từ upstream
        run: git fetch upstream

      # Bước 4: Hợp nhất (merge) các thay đổi vào nhánh chính của bạn
      - name: 4. Hợp nhất (merge) thay đổi từ upstream/main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git checkout main
          git merge upstream/main --no-edit

      # Bước 5: Đẩy (push) các thay đổi đã hợp nhất lên repository của bạn
      - name: 5. Đẩy các thay đổi lên fork của bạn
        run: git push origin main
