name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ (bạn có thể chỉnh)
  workflow_dispatch:     # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git user
        run: |
          git config user.name "lehuuhieuak"
          git config user.email "01643815296h@gmail.com.com"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/danny-avila/LibreChat.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git main
