name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày vào 00:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'lehuuhieuak'
          git config --global user.email '01643815296h@gmail.com'

      - name: Add upstream
        run: git remote add upstream https://github.com/danny-avila/LibreChat.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Checkout main
        run: git checkout main

      - name: Pull from origin
        run: git pull origin main

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main
          
      - name: Push changes
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${PAT}@github.com/lehuuhieuak/LibreChat.git main
